[project]
name = "mai2dat"
version = "1.0.0"
description = "Convert any video to CRIWARE's video file format."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rich>=14.2.0",
    "typer>=0.21.1",
    "wannacri>=0.3.1",
]
